on:
    pull_request:
      paths:
        - esp/**
    push:
      branches:
        - main
      paths:
        - esp/**

jobs:
    
    build:
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2
          target: esp32
          path: 'esp/weather'
          command: |
                    'sudo apt-get install -y clang-format clang-tidy
                    find . -name '*.h' -o -name '*.c' | xargs clang-format -i
                    git diff --exit-code
                    idf.py build
                    find . -name '*.c' | xargs clang-tidy --warnings-as-errors=* -p build/'