on:
    pull_request:
      paths:
        - esp/**
    push:
      branches:
        - main
      paths:
        - esp/**

jobs:

    build:
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install clang-format and  clang-tidy
        run: sudo apt-get -y install clang-format clang-tidy

      - name: clang-format check
        run: |
            find . -name "*.c" -o -name "*.h" | xargs clang-format -i -style=file
            git diff --exit-code

      - name : Install ESP-IDF
        run: |
            cd ~
            sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
            mkdir -p ~/esp_install
            cd ~/esp_install
            git clone -b v5.2.3 --recursive https://github.com/espressif/esp-idf.git
            cd ~/esp_install/esp-idf
            ./install.sh esp32
      - name: Build and clang-tidy check
        run: |
            . $HOME/esp_install/esp-idf/export.sh
            cd $GITHUB_WORKSPACE/esp/weather
            idf.py build
            find . -name "*.c" -o -name "*.h" | xargs clang-tidy -p build


