name: Spring mvn tests pipeline

on:
  push:
    branches:
      - main
    paths:
      - spring/**
  pull_request:
    paths:
      - spring/**
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run mvn tests
      working-directory: ./spring
      run: mvn test
